language: c++
compiler: g++

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90
  - sudo apt-get install valgrind
  - git submodule update --init --recursive
  - make test
#  - make python
  - sudo pip install cpp-coveralls
script:
  - LD_LIBRARY_PATH=libtap ./test
#  - PYTHONPATH=. python tests/test.py
after_success:
  - coveralls --exclude tests --exclude MessagingTelehash/MessagingTelehash.h --exclude telehash-c --exclude libtap --gcov-options '\-lp'
  - LD_LIBRARY_PATH=libtap G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --num-callers=40 ./test
