language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90
  - sudo apt-get install valgrind
  - git submodule update --init --recursive
  - pip install coverage coveralls
  - make test
  - python setup.py install

script:
  - LD_LIBRARY_PATH=libtap ./test
  - coverage run setup.py test -a "--doctest-modules --pep8 -v tests/"

after_success:
  - coverage report -m --include="storj/messaging/storjtelehash/*.py,storj/messaging/*.py"
  - pip install cpp-coveralls
  - coveralls --exclude tests --exclude telehash-c --exclude libtap --exclude cxx/telehashbinder_python.cpp --gcov-options '\-lp'
  - LD_LIBRARY_PATH=libtap G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --log-file=a.log --num-callers=40 ./test
  - cat a.log
